backend:
  name: git-gateway
  branch: main
media_folder: "assets/uploads"
public_folder: "/assets/uploads"
collections:
  - name: "productos"
    label: "Productos"
    folder: "_productos"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "TÃ­tulo", name: "title", widget: "string"}
      - {label: "Precio", name: "precio", widget: "number", value_type: "float"}
      - {label: "Foto", name: "imagen", widget: "image"}